### PR TITLE
Added a ResetView which shows the model name and a reset button. Move…

### PR DESCRIPTION
**Pull request by mbucknell**
…d the model-selection-container up to the top of the map (this is also where the ResetView goes.

I haven't yet changed the routing becuase the selectionModel is passed in to MapFilterView which @isuftin is working on.

Added a function to ModelCollection to retrieve the metadata model for the modelId.

### CODE REVIEW

**Comment by isuftin** [comment]
@mbucknell merged my stuff so you should be good

**Comment by mbucknell** [comment]
I think everything is working but can't test well because of geoserver issues so I'll wait to merge this until I can test more thoroughly.

**Comment by isuftin** [comment]
This branch needs fixin's!

**Comment by mbucknell** [comment]
I'm going to merge this even though testing has been hampered by geoserver weirdness.

**Pull request merged**
