### PR TITLE
IE height issue

### PR DESCRIPTION
**Pull request by mwernimont**
IE needs all containers to have height to allow % heights.

#model-selection-container was .model-selection-container in the less so it was receiving zero styles, which was odd, also the container has no content, but different issue.

z-index on the footer to avoid map overlapping it.

@isuftin Looking better?

### CODE REVIEW

**Comment by mbucknell** [comment]
@mwernimont, I had changed it to using a class name. We are having a philosophical discussion about whether to use class or ids in the backbone code. Ivan changed it back to id.

**Comment by isuftin** [comment]
You have a lot of very precise percentages and pixels here. Are you going for a very specific screen size?

**Comment by mwernimont** [comment]
Well the 89% is the only numbers listening to the screen size, the other 100% for the map-ui-container and map are only filling the #page-content-container which is the 89% previously mentioned.  I'm not for sure on the other top bars(region search and model-selection-container) as I don't know exactly what will fill them quite yet.  The sidebar I'm very confident will fit well on all the screen sizes SPARROW will be hitting.

**Comment by mwernimont** [comment]
@isuftin suggesting we use em's over pixels?

**Comment by isuftin** [comment]
@mwernimont Not necessarily suggesting anything. Was just wondering why so precise.

**Comment by mwernimont** [comment]
Was going off my mockups, matching the pixels of that layout

**Pull request merged**
